### ISSUE TITLE
CNAdid

### ISSUE THREAD

**Issue by Theoneee** [shuzilm-open-source/Get_Oaid_CNAdid#11]
```
"/sdcard/Android/ZHVzY2Lk"
```

这个文件是可以删除的。。一旦删除就没了。我拿的华为NOVA测试的，只会走这个方法。

**Comment by shuzilm-open-source** [comment]
可以线上产品获取，有值率很高。

**Comment by liyujiang-gzu** [comment]
CNAdId的原理主要是利用本机永久存储？
。。。
随机为本机生存一个标识串，然后依次利用以下存储方式:
1、sharedpreferences。
2、system.settings。
3、external storage。
。。。。

**Comment by linwenhui0** [comment]
我都获得不到，sd 卡的读写权限都开了

**Comment by liyujiang-gzu** [comment]
> 我都获得不到，sd 卡的读写权限都开了

Android 10已经没有存储权限的说法，外部存储的文件读写已经不同于传统方式。到了Android 11，谷歌貌似又增加了一个MANAGE_EXTRENAL_STORAGE的权限来方便读写外部存储的文件

**Comment by linwenhui0** [comment]
> > 我都获得不到，sd 卡的读写权限都开了
> 
> Android 10已经没有存储权限的说法，外部存储的文件读写已经不同于传统方式。到了Android 11，谷歌貌似又增加了一个MANAGE_EXTRENAL_STORAGE的权限来方便读写外部存储的文件

Android 10存在兼容模式，Android 11确实是增加了MANAGE_EXTRENAL_STORAGE来管理sd卡的文件权限，不过，把编译版本调低可以正常访问到sd卡上面的文件，我的意思是1、把没开兼容模式也取不到。2、非兼容模式有办法取的到吗
