### ISSUE TITLE
为啥华为上又能跑通

### ISSUE THREAD

**Issue by google-mirror** [shuzilm-open-source/Get_Oaid_CNAdid#19]
https://github.com/shuzilm-open-source/Get_Oaid_CNAdid/blob/master/OAID_Tool/app/src/main/java/com/example/oaid_tool/helpers/HWDeviceIDHelper.java

linkedBlockingQueue.take()和onServiceConnected死锁了, 如果在主线程调的话

**Comment by shuzilm-open-source** [comment]
这些示例代码 逻辑都能跑通，开发者要注意代码优化。
