### ISSUE TITLE
建议做成gradle可用的jar

### ISSUE THREAD

**Issue by badboy-tian** [shuzilm-open-source/Get_Oaid_CNAdid#3]
如题

**Comment by liyujiang-gzu** [comment]
参阅这个：

Step 1. Add the JitPack repository to your build file

gradle
maven
sbt
leiningen
Add it in your root build.gradle at the end of repositories:

	allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
Step 2. Add the dependency

	dependencies {
	        implementation 'com.github.gzu-liyujiang:Android_CN_OAID:-7b85337184-1'
	}
